### ISSUE TITLE
error while creating bag

### ISSUE THREAD

**Issue by soans1994** [TauraBots/Bag-of-Features#1]
curr_img = cv2.imread(img_list[0], 0)
IndexError: list index out of range

**Comment by guichristmann** [comment]
Did you structure your dataset for creating the bag like the Example dataset in the repo? 
And are you passing the arguments correctly?

**Comment by soans1994** [comment]
Yes i did is as per the instruction
python createBag.py Datasets 500 Bags

Traceback (most recent call last):
  File "createBag.py", line 63, in <module>
    kp_vector, des_vector = calcVectors(image_names)
  File "createBag.py", line 16, in calcVectors
    curr_img = cv2.imread(img_list[0], 0)
IndexError: list index out of range

**Comment by guichristmann** [comment]
Does your dataset contain images?
